// Code generated by "stringer -type=Status"; DO NOT EDIT.

package example

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StepUnknown-0]
	_ = x[StatusStarted-1]
	_ = x[StatusNameCreated-2]
	_ = x[StatusColourSet-3]
	_ = x[StatusAgeDefined-4]
	_ = x[StatusSentToSchool-5]
	_ = x[StatusSentToWork-6]
	_ = x[StatusFinishedSchool-7]
}

const _Status_name = "StepUnknownStatusStartedStatusNameCreatedStatusColourSetStatusAgeDefinedStatusSentToSchoolStatusSentToWorkStatusFinishedSchool"

var _Status_index = [...]uint8{0, 11, 24, 41, 56, 72, 90, 106, 126}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
